### PR TITLE
Added Discussion section into readme file

### LINKED ISSUE #8: Update Cake.UrlLoadDirective.Module README: Add link to GitHub Discussions
We've started using [GitHub Discussions](https://github.com/cake-build/cake/discussions) as the preferred communication channel moving forward (instead of Gitter) because it makes it easier to keep track of discussions in a structured way, especially if multiple discussions are happening at the same time. It also allows to search for previous questions/answers, which can be a helpful resource.

As such, we're recommending addin maintainers to update any links to Gitter to point to the GH discussions.

image

Template:

```markdown
## Discussion

For questions and to discuss ideas & feature requests, use the [GitHub discussions on the Cake GitHub repository](https://github.com/cake-build/cake/discussions), under the [Extension Q&A](https://github.com/cake-build/cake/discussions/categories/extension-q-a) category.

[![Join in the discussion on the Cake repository](https://img.shields.io/badge/GitHub-Discussions-green?logo=github)](https://github.com/cake-build/cake/discussions)
```

### PR DESCRIPTION
**Pull request by DiDoHH**
## Description
I added the suggested text into the readme file

## Related Issue
Fixes #8 

## Motivation and Context
#8 

## How Has This Been Tested?
Visually

## Types of changes
Doumentation 

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by augustoproiete** [comment]
@DiDoHH your changes have been merged, thanks for your contribution :+1:

**Comment by DiDoHH** [comment]
You're welcome

**Comment by DiDoHH** [comment]
Hello @augustoproiete, would you be so kind and mark this PR as "hacktoberfest-accepted"?

**Comment by augustoproiete** [comment]
I did it, but I'm curious why that would be needed :thinking: I thought the criteria to be counted as a valid PR would be *either* merge or tag, so your merged PRs should count without the tag (in theory) :man_shrugging:

**Comment by DiDoHH** [comment]
Hi @augustoproiete, I'm not sure, why that was needed, my overview shows, that this project is not participating.
2021-10-06 20_11_21-Hacktoberfest 2021

**Comment by augustoproiete** [comment]
Weird. Hope the tag works!

**Comment by DiDoHH** [comment]
Yes, it did. Thanks for your support.

**Pull request merged**
